Dnastrain/uirouters
great-lakes/project-egypt pull request #69
Opened 2018-06-27 21:29 UTC by dnastrain

Adding Routers for Generators, AddHub and NotFound to base UI, and stub pages for each.

Contributes to #38

2018-06-27 21:35 UTC, SarahSexton submitted a review, later dismissed

2018-06-27 21:39 UTC, ScruffyFurn requested changes
Please remove the "\<HubCreation \/>" from App.js file (I know it was only for debug )

2018-06-27 22:00 UTC, dwcares commented
@ScruffyFurn it looks like <hubcreation/> isn't in the content, but it's still in the import.

2018-06-27 22:07 UTC, ScruffyFurn approved these changes

2018-06-27 22:08 UTC, merged

2018-06-28 02:16 UTC, dwcares commented
Fixed #63